// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8vHLSmm_-ubmf1z-3MkvoFVvy_yH-Cu8',
    appId: '1:920323783981:web:864380a0a2e118c96ae7a4',
    messagingSenderId: '920323783981',
    projectId: 'mutiara-app',
    authDomain: 'mutiara-app.firebaseapp.com',
    storageBucket: 'mutiara-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6hRBZUkrc3ZqwYqpJA4qJ4thlk4QI7U',
    appId: '1:920323783981:android:afc0c642b9b3064a6ae7a4',
    messagingSenderId: '920323783981',
    projectId: 'mutiara-app',
    storageBucket: 'mutiara-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl28aLFwZRfB7Uvg6xUMDU4vF9JPLS6WQ',
    appId: '1:920323783981:ios:0acda263857a0cd56ae7a4',
    messagingSenderId: '920323783981',
    projectId: 'mutiara-app',
    storageBucket: 'mutiara-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl28aLFwZRfB7Uvg6xUMDU4vF9JPLS6WQ',
    appId: '1:920323783981:ios:0acda263857a0cd56ae7a4',
    messagingSenderId: '920323783981',
    projectId: 'mutiara-app',
    storageBucket: 'mutiara-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8vHLSmm_-ubmf1z-3MkvoFVvy_yH-Cu8',
    appId: '1:920323783981:web:a303b518e03e47c96ae7a4',
    messagingSenderId: '920323783981',
    projectId: 'mutiara-app',
    authDomain: 'mutiara-app.firebaseapp.com',
    storageBucket: 'mutiara-app.firebasestorage.app',
  );

}